#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -r steadyState
rm -r transient
rm *.out log.*

# printf "This is a dummy file at the moment. To finilize it, the Allrun tutorials must be capable of generating the entire mesh..."
# Source tutorial clean functions
# . $WM_PROJECT_DIR/bin/tools/CleanFunctions
#
# keepCases="rootCase"
# loseCases="steadyState transient"
#
# for caseName in $keepCases
# do
# (
#     cd $caseName || exit
#     foamCleanTutorials
# )
# done
#
# for caseName in $loseCases
# do
#     removeCase $caseName
# done

#------------------------------------------------------------------------------
