#!/bin/sh
exe="GeN-Foam"

# Start gnuplot if it exist
if command -v gnuplot &> /dev/null
then
    gnuplot -e "log='log.$exe'" residuals - &> /dev/null &
else
    echo "gnuplot could not be found"
fi

decomposePar -allRegions
mpirun -np 4 $exe -parallel | tee "log.$exe"
reconstructPar -allRegions

# Kill gnuplot if it was started
pkill -x gnuplot &> /dev/null &
