#!/bin/bash

# --- Run from this directory
cd ${0%/*} || exit 1

# --- Initialize the output file
resFile=test.out
rm $resFile
touch $resFile

# --- Run the simulation
echo -e "Run tutorial 1D_MSR_pointKinetics ...\n" | tee -a $resFile
./Allrun >> log.simulation
echo -e "Done running tutorial 1D_MSR_pointKinetics ...\n" | tee -a $resFile

# --- Check it ran
isConverge()
{
    folder=$1
    name=$2
    string=$(tail -3 ./$folder/log.GeN-Foam | grep End)
    if [ "$string" = "End" ]; then
        echo -e "$name has converged \n" | tee -a $resFile
    else
        echo -e "$name has NOT converged \n" | tee -a $resFile
        exit 1
    fi
}
isConverge steadyState "Steady state"
isConverge transient "Transient"
isConverge transientEnd "Transient end"

# --- Recover the results
power=$(grep totalPower ./transient/log.GeN-Foam | tail -1 | egrep -o "[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?.")
expectedAt=6.13794e+08

# --- Check that results are correct
echo "Power" | tee -a $resFile
if [ $power = $expectedAt ]; then
    echo "Perfect match:" | tee -a $resFile
    echo "    Expected  : $expectedAt" | tee -a $resFile
    echo "    Simulated : $power" | tee -a $resFile
else
    echo "Divergent results:" | tee -a $resFile
    echo "    Expected  : $expectedAt" | tee -a $resFile
    echo "    Simulated : $power" | tee -a $resFile
    exit 1
fi

# --- Exit successfully
exit 0
